### ISSUE TITLE
remote control for audacious, mplayer, vlc..

### ISSUE THREAD

**Issue by cosmos72** [cosmos72/twutils#2]
Clone and adapt twxmms2 to use DBus interface "org.mpris.MediaPlayer2"
it is a standard interface, supported by many audio/video players, including audacious, mplayer, vlc...

**Comment by Mirppc** [comment]
Ohh... VLC was one of the goals i was going to try and implement myself,  Audacious on the other hand might be a bit trickier as it is dependent on GTK.  I should test if VLC will work noX inside twin.  If so then all that would be needed is an interface.

**Comment by cosmos72** [comment]
I think there is a misunderstanding here.
My idea was to implement a modified version of twxmms2 that would **communicate** to a running (and unmodified) audacious, mplayer or vlc, acting as a kind of remote control. There are a lot of "applets" or desktop plugins doing this already, as for example http://mprisapplet.sourceforge.net/  and https://extensions.gnome.org/extension/438/mpris-22-player-indicator/

This is what twxmms2 does: connects to an existing xmms2d and send the commands start/stop/pause/skip N seconds/rewind N seconds/go to next track/go to previous track.

In my opinion, **porting** VLC, audacious, mplayer or any other **video** player to twin is quite pointless (unless you happen to like ascii-art videos). If I have to choose, I would rather spend time ensuring that mp3blaster (or some other recent text-only audio player, in case mp3blaster is stalled) runs smoothly inside a twin terminal. Or better yet, implement a twin-enabled remote control for them, as I was proposing.

**Comment by cosmos72** [comment]
In progress :)

**Comment by cosmos72** [comment]
completed :)

see https://github.com/cosmos72/twutils/tree/master/twplayer_remote
